In [1]:
import os;
import json;
import builtins
import duckdb
import pandas as pd;
import matplotlib.pyplot as plt

def get_dataset_from_testcase(run):
    pos = run.find("_threads")
    return run[0:pos]

dirs = [
    '/media/datahdd/chesetti/sponge/join_hdd',
    '/media/datahdd/chesetti/sponge/join_hdd_all'
]
runs = []
for dir in dirs:
 for test_case in os.listdir(dir):
    if test_case == 'build':
        continue
    for run_name in os.listdir(os.path.join(dir, test_case, 'outputs', 'results')):
        if (run_name=="run"):
           continue
        json_file = builtins.open(os.path.join(dir, test_case, 'outputs', 'results',  run_name))
        run = (json.load(json_file))
        run['dataset'] = get_dataset_from_testcase(test_case)
        runs.append(run)
    for run_name in os.listdir(os.path.join(dir, test_case, 'outputs', 'results', 'run')):
        json_file = builtins.open(os.path.join(dir, test_case, 'outputs', 'results', 'run', run_name))
        run = (json.load(json_file))
        run['dataset'] = get_dataset_from_testcase(test_case)
        runs.append(run)
df = pd.json_normalize(runs)
print(df.columns)
display(df)

Index(['command', 'dataset', 'result.checksum', 'result.duration_ns',
       'result.duration_sec', 'result.inner_disk_fetch',
       'result.inner_disk_fetch_size', 'result.inner_total_bytes_fetched',
       'result.num_output_keys', 'result.outer_disk_fetch',
       'result.outer_disk_fetch_size', 'result.outer_total_bytes_fetched',
       'spec.algo', 'spec.algo_name', 'spec.check_checksum', 'spec.common_key',
       'spec.inner_table', 'spec.key_size', 'spec.key_type',
       'spec.load_sstable_in_mem', 'spec.name', 'spec.num_threads',
       'spec.outer_table', 'spec.result_path', 'spec.value_size',
       'spec.write_result_to_disk', 'iostat.bytes_read', 'iostat.bytes_wrtn',
       'spec.index.epsilon', 'spec.index.search', 'spec.index.type',
       'spec.index.leaf_size_in_pages'],
      dtype='object')

,command,dataset,result.checksum,result.duration_ns,result.duration_sec,result.inner_disk_fetch,result.inner_disk_fetch_size,result.inner_total_bytes_fetched,result.num_output_keys,result.outer_disk_fetch,...,spec.outer_table,spec.result_path,spec.value_size,spec.write_result_to_disk,iostat.bytes_read,iostat.bytes_wrtn,spec.index.epsilon,spec.index.search,spec.index.type,spec.index.leaf_size_in_pages
0,/media/datahdd/chesetti/sponge/join_hdd/build/...,fb,0,17678435595,17.678436,781239,4096,3199954944,199924,781,...,/media/datahdd/chesetti/sponge/join_hdd/fb_thr...,/media/datahdd/chesetti/sponge/join_hdd/fb_thr...,8,True,3132920000,2492000,NaN,NaN,NaN,NaN
1,/media/datahdd/chesetti/sponge/join_hdd/build/...,fb,0,24238784339,24.238784,390625,8192,3199999984,19031563,74343,...,/media/datahdd/chesetti/sponge/join_hdd/fb_thr...,/media/datahdd/chesetti/sponge/join_hdd/fb_thr...,8,True,3426100000,140000,256.0,binary,sampledflatpgm256,NaN
2,/media/datahdd/chesetti/sponge/join_hdd/build/...,fb,0,46238812893,46.238813,781250,4096,3199999984,1990059,0,...,/media/datahdd/chesetti/sponge/join_hdd/fb_thr...,/media/datahdd/chesetti/sponge/join_hdd/fb_thr...,8,True,3160848000,21240000,NaN,NaN,NaN,NaN
3,/media/datahdd/chesetti/sponge/join_hdd/build/...,fb,0,86467947596,86.467948,781250,4096,3199999984,199999999,0,...,/media/datahdd/chesetti/sponge/join_hdd/fb_thr...,/media/datahdd/chesetti/sponge/join_hdd/fb_thr...,8,True,6254704000,2561136000,NaN,NaN,NaN,NaN
4,/media/datahdd/chesetti/sponge/join_hdd/build/...,fb,0,46505878337,46.505878,781250,4096,3199999984,1990059,0,...,/media/datahdd/chesetti/sponge/join_hdd/fb_thr...,/media/datahdd/chesetti/sponge/join_hdd/fb_thr...,8,True,3160828000,26996000,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67,/media/datahdd/chesetti/sponge/join_hdd/build/...,fb,0,21745714778,21.745715,781250,4096,3199999984,199924,0,...,/media/datahdd/chesetti/sponge/join_hdd/fb_thr...,/media/datahdd/chesetti/sponge/join_hdd/fb_thr...,8,True,3132836000,3160000,NaN,NaN,NaN,NaN
68,/media/datahdd/chesetti/sponge/join_hdd/build/...,fb,0,52293135692,52.293136,8578348,8192,70273820496,199999999,781250,...,/media/datahdd/chesetti/sponge/join_hdd/fb_thr...,/media/datahdd/chesetti/sponge/join_hdd/fb_thr...,8,True,6253848000,1774864000,256.0,binary,sampledflatpgm256,NaN
69,/media/datahdd/chesetti/sponge/join_hdd/build/...,fb,0,83211630705,83.211631,781250,4096,3199999984,199999999,781250,...,/media/datahdd/chesetti/sponge/join_hdd/fb_thr...,/media/datahdd/chesetti/sponge/join_hdd/fb_thr...,8,True,6254716000,2982588000,NaN,NaN,NaN,NaN
70,/media/datahdd/chesetti/sponge/join_hdd/build/...,fb,0,23479188488,23.479188,781250,4096,3199999984,19031563,74343,...,/media/datahdd/chesetti/sponge/join_hdd/fb_thr...,/media/datahdd/chesetti/sponge/join_hdd/fb_thr...,8,True,3427112000,144000,NaN,NaN,NaN,NaN
71,/media/datahdd/chesetti/sponge/join_hdd/build/...,fb,0,19123798575,19.123799,721113,4096,2953678832,1990059,7774,...,/media/datahdd/chesetti/sponge/join_hdd/fb_thr...,/media/datahdd/chesetti/sponge/join_hdd/fb_thr...,8,True,3168804000,14056000,256.0,binary,btree,1.0

In [2]:

epsilon = {
    "pgm256": 256,
    "pgm1024": 1024,
    "pgm2048": 2048,
    "flatpgm256": 256,
    "flatpgm1024": 1024,
    "flatpgm2048": 2048,
    "flatpgm4096": 4096,
    "flatpgm8192": 8192,
    "hashjoin": 0,
    "btree": 0,
    "sj": 0,
    "sj2": 0,
    "standard_merge": 0
};
def indexType(x):
    if "pgm" in x:
        return "PGM"
    elif "btree" in x:
        return "BTREE"
    return "NA"

df["threads"] = df["spec.num_threads"]
df["duration_sec"] = df["result.duration_ns"] / (1000000000)
df["inner_disk_fetch"] = df["result.inner_disk_fetch"]
df['result_num_keys'] = df['result.num_output_keys']
df["ratio"] = df["spec.common_key"]
df["algo"] = df["spec.algo_name"]
df["epsilon"] = df["spec.index.epsilon"]
df["inner_bytes_fetched"] = df["result.inner_total_bytes_fetched"]
df["index_type"] = df["spec.algo_name"].map(lambda x: indexType(x))
df['disk_read_gb'] = df['iostat.bytes_read']/1e9
df['disk_wrtn_gb'] = df['iostat.bytes_wrtn']/1e9
#df['cdisk_read_gb'] = df['cgroup_iostat.bytes_read']/1e9
#df['cdisk_wrtn_gb'] = df['cgroup_iostat.bytes_wrtn']/1e9
df['checksum'] = df['result.checksum']
df['threads'] = df['spec.num_threads']

df['dataset'].unique()
df['result.num_output_keys'].unique()
duckdb.sql("SELECT * FROM df WHERE dataset='fb'")

┌──────────────────────┬─────────┬─────────────────┬────────────────────┬───┬──────────────┬──────────────┬──────────┐
│       command        │ dataset │ result.checksum │ result.duration_ns │ … │ disk_read_gb │ disk_wrtn_gb │ checksum │
│       varchar        │ varchar │      int64      │       int64        │   │    double    │    double    │  int64   │
├──────────────────────┼─────────┼─────────────────┼────────────────────┼───┼──────────────┼──────────────┼──────────┤
│ /media/datahdd/che…  │ fb      │               0 │        17678435595 │ … │      3.13292 │     0.002492 │        0 │
│ /media/datahdd/che…  │ fb      │               0 │        24238784339 │ … │       3.4261 │      0.00014 │        0 │
│ /media/datahdd/che…  │ fb      │               0 │        46238812893 │ … │     3.160848 │      0.02124 │        0 │
│ /media/datahdd/che…  │ fb      │               0 │        86467947596 │ … │     6.254704 │     2.561136 │        0 │
│ /media/datahdd/che…  │ fb      │               0 │        46505878337 │ … │     3.160828 │     0.026996 │        0 │
│ /media/datahdd/che…  │ fb      │               0 │        24173486990 │ … │     3.426228 │      0.00016 │        0 │
│ /media/datahdd/che…  │ fb      │               0 │        63899306203 │ … │     6.262716 │     2.484896 │        0 │
│ /media/datahdd/che…  │ fb      │               0 │        25831970594 │ … │     3.427072 │      0.28944 │        0 │
│ /media/datahdd/che…  │ fb      │               0 │        17803527316 │ … │      2.90958 │     0.000244 │        0 │
│ /media/datahdd/che…  │ fb      │               0 │        25606680178 │ … │     3.435124 │     0.260524 │        0 │
│          ·           │ ·       │               · │             ·      │ · │         ·    │         ·    │        · │
│          ·           │ ·       │               · │             ·      │ · │         ·    │         ·    │        · │
│          ·           │ ·       │               · │             ·      │ · │         ·    │         ·    │        · │
│ /media/datahdd/che…  │ fb      │               0 │        58130965624 │ … │     6.262828 │     2.595972 │        0 │
│ /media/datahdd/che…  │ fb      │               0 │        24393129358 │ … │     3.435128 │     0.000108 │        0 │
│ /media/datahdd/che…  │ fb      │               0 │        21145260196 │ … │     3.132876 │     0.002424 │        0 │
│ /media/datahdd/che…  │ fb      │               0 │        18926013314 │ … │     3.159924 │     0.018576 │        0 │
│ /media/datahdd/che…  │ fb      │               0 │        82342224335 │ … │     6.254764 │     3.035784 │        0 │
│ /media/datahdd/che…  │ fb      │               0 │        21745714778 │ … │     3.132836 │      0.00316 │        0 │
│ /media/datahdd/che…  │ fb      │               0 │        52293135692 │ … │     6.253848 │     1.774864 │        0 │
│ /media/datahdd/che…  │ fb      │               0 │        83211630705 │ … │     6.254716 │     2.982588 │        0 │
│ /media/datahdd/che…  │ fb      │               0 │        23479188488 │ … │     3.427112 │     0.000144 │        0 │
│ /media/datahdd/che…  │ fb      │               0 │        19123798575 │ … │     3.168804 │     0.014056 │        0 │
├──────────────────────┴─────────┴─────────────────┴────────────────────┴───┴──────────────┴──────────────┴──────────┤
│ 72 rows (20 shown)                                                                            44 columns (7 shown) │
└────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

In [7]:
def print_for_dataset(dataset, algos):
    print("## " + dataset)
    algo_filter = ''
    for algo in algos:
        algo_filter = algo_filter + f" OR algo='{algo}'"
    algo_filter = algo_filter[3:]
    rows = duckdb.sql(
        " SELECT ratio, algo, MEDIAN(duration_sec) as v FROM df"
        f" WHERE threads=1  AND dataset='{dataset}'"
        f" AND ({algo_filter})"
        " GROUP BY dataset, threads, ratio, algo"
        " ORDER BY ratio, threads"
    ).df()
    rows = rows.pivot(index='ratio', values='v', columns='algo')
    print(rows[algos].to_markdown())
    rows[algos].to_csv('/home/chesetti/Repos/LearnedJoinDiskExp/experiments/results/join_hdd/'+dataset+'.txt')



algos = ['lsj_sampledflatpgm256', 'inlj_btree256',  'sort_join', 'hash_join']
print_for_dataset("fb", algos)
print_for_dataset("wiki", algos)
print_for_dataset("uniform_dense", algos)
print_for_dataset("uniform_sparse", algos)
print_for_dataset("normal", algos)
print_for_dataset("lognormal", algos)
#print_for_dataset("wiki", algos)
#print_for_dataset("osm", algos)
#print_for_dataset("books", algos)

## fb
|   ratio |   lsj_sampledflatpgm256 |   inlj_btree256 |   sort_join |   hash_join |
|--------:|------------------------:|----------------:|------------:|------------:|
|       1 |                 82.8801 |         56.4065 |     83.1547 |     86.4679 |
|      10 |                 24.4542 |         24.6316 |     23.642  |     56.2128 |
|     100 |                 18.6989 |         18.6072 |     18.8502 |     46.4556 |
|    1000 |                 17.7203 |         17.6732 |     17.6784 |     21.1792 |

In [20]:
rows = duckdb.sql(
    " SELECT ratio, algo, MEDIAN(duration_sec) as v FROM df"
    f" WHERE threads=1 AND (algo='hash_join' OR algo='sort_join' or epsilon='256') AND dataset='fb'"
    " GROUP BY dataset, threads, ratio, algo"
    " ORDER BY ratio, threads"
).df()
display(rows.pivot(index='ratio', values='v', columns='algo'))

rows = duckdb.sql(
    " SELECT ratio, algo, MEDIAN(duration_sec) as v FROM df"
    f" WHERE threads=1 AND (algo='hash_join' OR algo='sort_join' or epsilon='256') AND dataset='fb'"
    " AND (algo='lsj_pgm256' OR algo='lsj_flatpgm256' OR algo='lsj_sampledpgm256' OR algo='lsj_sampledflatpgm256')"
    " GROUP BY dataset, threads, ratio, algo"
    " ORDER BY ratio, threads"
).df()
display(rows.pivot(index='ratio', values='v', columns='algo'))

rows = duckdb.sql(
    " SELECT ratio, algo, MEDIAN(duration_sec) as v FROM df"
    f" WHERE threads=1 AND (algo='hash_join' OR algo='sort_join' or epsilon='1024') AND dataset='wiki'"
    " GROUP BY dataset, threads, ratio, algo"
    " ORDER BY ratio, threads"
).df()
display(rows.pivot(index='ratio', values='v', columns='algo'))

rows = duckdb.sql(
    " SELECT ratio, algo, MEDIAN(duration_sec) as v FROM df"
    f" WHERE threads=1 AND (algo='hash_join' OR algo='sort_join' or epsilon='256') AND dataset='wiki'"
    " AND (algo='lsj_pgm256' OR algo='lsj_flatpgm256' OR algo='lsj_sampledpgm256' OR algo='lsj_sampledflatpgm256')"
    " GROUP BY dataset, threads, ratio, algo"
    " ORDER BY ratio, threads"
).df()
display(rows.pivot(index='ratio', values='v', columns='algo'))

rows = duckdb.sql(
    " SELECT ratio, algo, MEDIAN(duration_sec) as v FROM df"
    f" WHERE threads=1 AND (algo='hash_join' OR algo='sort_join' or epsilon='4096') AND dataset='books'"
    " GROUP BY dataset, threads, ratio, algo"
    " ORDER BY ratio, threads"
).df()
display(rows.pivot(index='ratio', values='v', columns='algo'))

rows = duckdb.sql(
    " SELECT ratio, algo, MEDIAN(duration_sec) as v FROM df"
    f" WHERE threads=1 AND (algo='hash_join' OR algo='sort_join' or epsilon='256') AND dataset='osm'"
    " AND (algo='lsj_pgm256' OR algo='lsj_flatpgm256' OR algo='lsj_sampledpgm256' OR algo='lsj_sampledflatpgm256')"
    " GROUP BY dataset, threads, ratio, algo"
    " ORDER BY ratio, threads"
).df()
display(rows.pivot(index='ratio', values='v', columns='algo'))

algo,hash_join,inlj_btree256,inlj_sampledflatpgm256,lsj_btree256,lsj_sampledflatpgm256,sort_join
ratio,,,,,,
1,80.931304,49.388665,44.882598,55.784585,32.612449,31.299311
10,55.292828,8.003186,8.061300,8.363397,7.774270,8.724903
100,45.841991,6.726388,6.664628,6.787620,6.632520,7.177175
1000,21.057477,22.401654,18.125491,22.804902,18.035658,7.082692

algo   lsj_sampledflatpgm256
ratio
1                  32.612449
10                  7.774270
100                 6.632520
1000               18.035658

Empty DataFrame
Columns: []
Index: []

Empty DataFrame
Columns: []
Index: []

Empty DataFrame
Columns: []
Index: []

Empty DataFrame
Columns: []
Index: []

In [21]:
rows = duckdb.sql(
    " SELECT ratio, algo, MEDIAN(inner_disk_fetch) as v FROM df"
    f" WHERE threads=1 AND (algo='hash_join' OR algo='sort_join' or epsilon='256') AND dataset='wiki'"
    " GROUP BY dataset, threads, ratio, algo"
    " ORDER BY ratio, threads"
).df()
display(rows.pivot(index='ratio', values='v', columns='algo'))

rows = duckdb.sql(
    " SELECT ratio, algo, MEDIAN(inner_disk_fetch) as v FROM df"
    f" WHERE threads=1 AND (algo='hash_join' OR algo='sort_join' or epsilon='1024') AND dataset='wiki'"
    " GROUP BY dataset, threads, ratio, algo"
    " ORDER BY ratio, threads"
).df()
display(rows.pivot(index='ratio', values='v', columns='algo'))

rows = duckdb.sql(
    " SELECT ratio, algo, MEDIAN(inner_disk_fetch) as v FROM df"
    f" WHERE threads=1 AND (algo='hash_join' OR algo='sort_join' or epsilon='4096') AND dataset='wiki'"
    " GROUP BY dataset, threads, ratio, algo"
    " ORDER BY ratio, threads"
).df()
display(rows.pivot(index='ratio', values='v', columns='algo'))

Empty DataFrame
Columns: []
Index: []

Empty DataFrame
Columns: []
Index: []

Empty DataFrame
Columns: []
Index: []

In [8]:
def print_for_dataset(dataset, algos):
    print("## " + dataset)
    algo_filter = ''
    for algo in algos:
        algo_filter = algo_filter + f" OR algo='{algo}'"
    algo_filter = algo_filter[3:]
    rows = duckdb.sql(
        " SELECT ratio, algo, MEDIAN(duration_sec) as v FROM df"
        f" WHERE threads=1  AND dataset='{dataset}'"
        f" AND ({algo_filter})"
        " GROUP BY dataset, threads, ratio, algo"
        " ORDER BY ratio, threads"
    ).df()
    rows = rows.pivot(index='ratio', values='v', columns='algo')
    print(rows[algos].to_markdown())
    rows[algos].to_csv('all_indexes/'+dataset+'.csv')



algos = ['lsj_sampledflatpgm256', 'lsj_btree256',  'sort_join', 'hash_join']
print_for_dataset("fb", algos)
print_for_dataset("wiki", algos)
print_for_dataset("osm", algos)
print_for_dataset("books", algos)

## fb

BinderException: Binder Error: Referenced column "threads" not found in FROM clause!
Candidate bindings: "df.dataset"

In [34]:
algos = ['lsj_sampledflatpgm256', 'lsj_flatpgm256', 'lsj_radixspline256', 'lsj_rmi' , 'lsj_btree256', 'sort_join']
print_for_dataset("fb", algos)
print_for_dataset("wiki", algos)
print_for_dataset("osm", algos)
print_for_dataset("books", algos)

## fb
|   ratio |   lsj_sampledflatpgm256 |   lsj_flatpgm256 |   lsj_radixspline256 |   lsj_rmi |   lsj_btree256 |   sort_join |
|--------:|------------------------:|-----------------:|---------------------:|----------:|---------------:|------------:|
|       1 |               23.2294   |        22.4319   |            25.6702   | 20.3287   |       42.3009  |    11.7042  |
|      10 |                3.68178  |         3.45073  |             4.30738  |  3.76312  |        5.83421 |     4.45029 |
|     100 |                0.98362  |         1.01192  |             1.46279  |  1.25237  |        1.57196 |     3.12833 |
|    1000 |                0.385151 |         0.353513 |             0.374326 |  0.275802 |        0.31908 |     2.86744 |
## wiki
|   ratio |   lsj_sampledflatpgm256 |   lsj_flatpgm256 |   lsj_radixspline256 |   lsj_btree256 |   sort_join |
|--------:|------------------------:|-----------------:|---------------------:|---------------:|------------:|
|       1 |               10.1179   |         9.45712  |             9.97239  |      19.3136   |     5.38747 |
|      10 |                3.07369  |         2.50171  |             3.14674  |       4.90736  |     2.74042 |
|     100 |                0.698167 |         0.56145  |             0.854485 |       0.8996   |     1.33415 |
|    1000 |                0.213931 |         0.208535 |             0.377251 |       0.322383 |     1.68557 |
## osm
|   ratio |   lsj_sampledflatpgm256 |   lsj_flatpgm256 |   lsj_radixspline256 |   lsj_rmi |   lsj_btree256 |   sort_join |
|--------:|------------------------:|-----------------:|---------------------:|----------:|---------------:|------------:|
|       1 |               72.8033   |        73.47     |             83.6905  |  85.1446  |      175.609   |     45.4784 |
|      10 |                7.99908  |         7.29272  |             13.9856  |  12.8359  |       22.2175  |     15.2134 |
|     100 |                0.840453 |         1.265    |              4.30599 |   4.21186 |        4.68381 |     11.2403 |
|    1000 |                0.146099 |         0.140748 |              1.23905 |   1.68892 |        1.11332 |     10.7955 |
## books
|   ratio |   lsj_sampledflatpgm256 |   lsj_flatpgm256 |   lsj_radixspline256 |   lsj_rmi |   lsj_btree256 |   sort_join |
|--------:|------------------------:|-----------------:|---------------------:|----------:|---------------:|------------:|
|       1 |               72.8343   |        73.6028   |             83.7642  | 78.908    |      174.423   |     45.1136 |
|      10 |                7.2696   |         6.94197  |             13.8679  | 12.7151   |       22.2364  |     15.456  |
|     100 |                0.914571 |         1.16784  |              4.35452 |  3.6482   |        4.84053 |     11.1811 |
|    1000 |                0.128371 |         0.131493 |              1.44302 |  0.936506 |        1.27291 |     10.9385 |

In [29]:
algos = ['lsj_radixspline256', 'lsj_radixspline1024', 'lsj_radixspline4096']
print_for_dataset("fb", algos)
print_for_dataset("wiki", algos)
print_for_dataset("osm", algos)
print_for_dataset("books", algos)

## fb

BinderException: Binder Error: Referenced column "threads" not found in FROM clause!
Candidate bindings: "df.dataset"