In [19]:
import os;
import json;
import builtins
import duckdb
import pandas as pd;
import matplotlib.pyplot as plt

def get_dataset_from_testcase(run):
    return run.split('_')[0]

dirs = [
    '/home/chesetti/Repos/LearnedJoinDiskExp/sponge/test',
]
runs = []
for dir in dirs:
 for test_case in os.listdir(dir):
    if test_case == 'build':
        continue
    for run_name in os.listdir(os.path.join(dir, test_case, 'outputs', 'results')):
        if (run_name=="run"):
           continue
        json_file = builtins.open(os.path.join(dir, test_case, 'outputs', 'results',  run_name))
        run = (json.load(json_file))
        run['dataset'] = get_dataset_from_testcase(test_case)
        runs.append(run)
    for run_name in os.listdir(os.path.join(dir, test_case, 'outputs', 'results', 'run')):
        json_file = builtins.open(os.path.join(dir, test_case, 'outputs', 'results', 'run', run_name))
        run = (json.load(json_file))
        run['dataset'] = get_dataset_from_testcase(test_case)
        runs.append(run)
df = pd.json_normalize(runs)
print(df.columns)
display(df)

Index(['command', 'dataset', 'result.checksum', 'result.duration_ns',
       'result.duration_sec', 'result.inner_disk_fetch',
       'result.inner_disk_fetch_size', 'result.inner_total_bytes_fetched',
       'result.num_output_keys', 'result.outer_disk_fetch',
       'result.outer_disk_fetch_size', 'result.outer_total_bytes_fetched',
       'spec.algo', 'spec.algo_name', 'spec.check_checksum', 'spec.common_key',
       'spec.index.epsilon', 'spec.index.search', 'spec.index.type',
       'spec.inner_table', 'spec.key_size', 'spec.key_type',
       'spec.load_sstable_in_mem', 'spec.name', 'spec.num_threads',
       'spec.outer_table', 'spec.result_path', 'spec.value_size',
       'spec.write_result_to_disk', 'iostat.bytes_read', 'iostat.bytes_wrtn'],
      dtype='object')

,command,dataset,result.checksum,result.duration_ns,result.duration_sec,result.inner_disk_fetch,result.inner_disk_fetch_size,result.inner_total_bytes_fetched,result.num_output_keys,result.outer_disk_fetch,...,spec.key_type,spec.load_sstable_in_mem,spec.name,spec.num_threads,spec.outer_table,spec.result_path,spec.value_size,spec.write_result_to_disk,iostat.bytes_read,iostat.bytes_wrtn
0,numactl -N 0 -m 0 sponge/test/build/benchmark_...,fb,E7D3487C0B68451EE9D985B8CFDB03AE,1235234528,1.235235,367436,8192,3010031760,1990014,7774,...,uint64,False,lsj_flatpgm256100run_2,1,sponge/test/fb_threads=1/inputs/input100,sponge/test/fb_threads=1/outputs/lsj_flatpgm25...,8,True,6452000,0
1,numactl -N 0 -m 0 sponge/test/build/benchmark_...,fb,E7D3487C0B68451EE9D985B8CFDB03AE,1504859801,1.504860,535395,8192,4385951888,1990014,7774,...,uint64,False,inlj_flatpgm256100run_1,1,sponge/test/fb_threads=1/inputs/input100,sponge/test/fb_threads=1/outputs/inlj_flatpgm2...,8,True,612000,4000
2,numactl -N 0 -m 0 sponge/test/build/benchmark_...,fb,E7D3487C0B68451EE9D985B8CFDB03AE,5182373650,5.182374,781250,4096,3199999984,1990014,7774,...,uint64,False,sort_join100run_2,1,sponge/test/fb_threads=1/inputs/input100,sponge/test/fb_threads=1/outputs/sort_join_run...,8,True,3168000,840000
3,numactl -N 0 -m 0 sponge/test/build/benchmark_...,fb,E7D3487C0B68451EE9D985B8CFDB03AE,3688843941,3.688844,781250,4096,3199999984,1990014,7774,...,uint64,False,sort_join100run_1,1,sponge/test/fb_threads=1/inputs/input100,sponge/test/fb_threads=1/outputs/sort_join_run...,8,True,5660000,54828000
4,numactl -N 0 -m 0 sponge/test/build/benchmark_...,fb,E7D3487C0B68451EE9D985B8CFDB03AE,1498583426,1.498583,535395,8192,4385951888,1990014,7774,...,uint64,False,inlj_flatpgm256100run_2,1,sponge/test/fb_threads=1/inputs/input100,sponge/test/fb_threads=1/outputs/inlj_flatpgm2...,8,True,3604000,376000
5,numactl -N 0 -m 0 sponge/test/build/benchmark_...,fb,E7D3487C0B68451EE9D985B8CFDB03AE,973323821,0.973324,367436,8192,3010031760,1990014,7774,...,uint64,False,lsj_flatpgm256100run_0,1,sponge/test/fb_threads=1/inputs/input100,sponge/test/fb_threads=1/outputs/lsj_flatpgm25...,8,True,1068000,0
6,numactl -N 0 -m 0 sponge/test/build/benchmark_...,fb,E7D3487C0B68451EE9D985B8CFDB03AE,3749177037,3.749177,781250,4096,3199999984,1990014,7774,...,uint64,False,sort_join100run_0,1,sponge/test/fb_threads=1/inputs/input100,sponge/test/fb_threads=1/outputs/sort_join_run...,8,True,51376000,344000
7,numactl -N 0 -m 0 sponge/test/build/benchmark_...,fb,E7D3487C0B68451EE9D985B8CFDB03AE,1462599577,1.462600,535395,8192,4385951888,1990014,7774,...,uint64,False,inlj_flatpgm256100run_0,1,sponge/test/fb_threads=1/inputs/input100,sponge/test/fb_threads=1/outputs/inlj_flatpgm2...,8,True,8000,1244000
8,numactl -N 0 -m 0 sponge/test/build/benchmark_...,fb,E7D3487C0B68451EE9D985B8CFDB03AE,2952323933,2.952324,367436,8192,3010031760,1990014,7774,...,uint64,False,lsj_flatpgm256100run_1,1,sponge/test/fb_threads=1/inputs/input100,sponge/test/fb_threads=1/outputs/lsj_flatpgm25...,8,True,3155856000,280000

In [21]:

epsilon = {
    "pgm256": 256,
    "pgm1024": 1024,
    "pgm2048": 2048,
    "flatpgm256": 256,
    "flatpgm1024": 1024,
    "flatpgm2048": 2048,
    "flatpgm4096": 4096,
    "flatpgm8192": 8192,
    "hashjoin": 0,
    "btree": 0,
    "sj": 0,
    "sj2": 0,
    "standard_merge": 0
};
def indexType(x):
    if "pgm" in x:
        return "PGM"
    elif "btree" in x:
        return "BTREE"
    return "NA"

df["threads"] = df["spec.num_threads"]
df["duration_sec"] = df["result.duration_ns"] / (1000000000)
df["inner_disk_fetch"] = df["result.inner_disk_fetch"]
df['result_num_keys'] = df['result.num_output_keys']
df["ratio"] = df["spec.common_key"]
df["algo"] = df["spec.algo_name"]
df["epsilon"] = df["spec.index.epsilon"]
df["inner_bytes_fetched"] = df["result.inner_total_bytes_fetched"]
df["index_type"] = df["spec.algo_name"].map(lambda x: indexType(x))
df['disk_read_gb'] = df['iostat.bytes_read']/1e9
df['disk_wrtn_gb'] = df['iostat.bytes_wrtn']/1e9
#df['cdisk_read_gb'] = df['cgroup_iostat.bytes_read']/1e9
#df['cdisk_wrtn_gb'] = df['cgroup_iostat.bytes_wrtn']/1e9

df['dataset'].unique()
df['result.num_output_keys'].unique()
duckdb.sql("SELECT * FROM df WHERE dataset='fb'")

┌──────────────────────┬─────────┬──────────────────────┬───┬────────────┬──────────────┬──────────────┐
│       command        │ dataset │   result.checksum    │ … │ index_type │ disk_read_gb │ disk_wrtn_gb │
│       varchar        │ varchar │       varchar        │   │  varchar   │    double    │    double    │
├──────────────────────┼─────────┼──────────────────────┼───┼────────────┼──────────────┼──────────────┤
│ numactl -N 0 -m 0 …  │ fb      │ E7D3487C0B68451EE9…  │ … │ PGM        │     0.006452 │          0.0 │
│ numactl -N 0 -m 0 …  │ fb      │ E7D3487C0B68451EE9…  │ … │ PGM        │     0.000612 │        4e-06 │
│ numactl -N 0 -m 0 …  │ fb      │ E7D3487C0B68451EE9…  │ … │ NA         │     0.003168 │      0.00084 │
│ numactl -N 0 -m 0 …  │ fb      │ E7D3487C0B68451EE9…  │ … │ NA         │      0.00566 │     0.054828 │
│ numactl -N 0 -m 0 …  │ fb      │ E7D3487C0B68451EE9…  │ … │ PGM        │     0.003604 │     0.000376 │
│ numactl -N 0 -m 0 …  │ fb      │ E7D3487C0B68451EE9…  │ … │ PGM        │     0.001068 │          0.0 │
│ numactl -N 0 -m 0 …  │ fb      │ E7D3487C0B68451EE9…  │ … │ NA         │     0.051376 │     0.000344 │
│ numactl -N 0 -m 0 …  │ fb      │ E7D3487C0B68451EE9…  │ … │ PGM        │        8e-06 │     0.001244 │
│ numactl -N 0 -m 0 …  │ fb      │ E7D3487C0B68451EE9…  │ … │ PGM        │     3.155856 │      0.00028 │
├──────────────────────┴─────────┴──────────────────────┴───┴────────────┴──────────────┴──────────────┤
│ 9 rows                                                                          42 columns (6 shown) │
└──────────────────────────────────────────────────────────────────────────────────────────────────────┘

In [22]:
print(duckdb.sql("SELECT RATIO,ALGO,INDEX_TYPE,DISK_READ_GB,DISK_WRTN_GB,DURATION_SEC FROM df WHERE dataset='fb' ORDER BY ALGO").df().to_markdown())

|    |   ratio | algo            | index_type   |   disk_read_gb |   disk_wrtn_gb |   duration_sec |
|---:|--------:|:----------------|:-------------|---------------:|---------------:|---------------:|
|  0 |     100 | inlj_flatpgm256 | PGM          |       0.000612 |       4e-06    |       1.50486  |
|  1 |     100 | inlj_flatpgm256 | PGM          |       0.003604 |       0.000376 |       1.49858  |
|  2 |     100 | inlj_flatpgm256 | PGM          |       8e-06    |       0.001244 |       1.4626   |
|  3 |     100 | lsj_flatpgm256  | PGM          |       0.006452 |       0        |       1.23523  |
|  4 |     100 | lsj_flatpgm256  | PGM          |       0.001068 |       0        |       0.973324 |
|  5 |     100 | lsj_flatpgm256  | PGM          |       3.15586  |       0.00028  |       2.95232  |
|  6 |     100 | sort_join       | NA           |       0.003168 |       0.00084  |       5.18237  |
|  7 |     100 | sort_join       | NA           |       0.00566  |       0.054828 |       3.68884  |
|  8 |     100 | sort_join       | NA           |       0.051376 |       0.000344 |       3.74918  |

In [12]:
rows = duckdb.sql(
    " SELECT ratio, algo, MEDIAN(duration_sec) as v FROM df"
    f" WHERE threads=1 AND (algo='hash_join' OR algo='sort_join' or epsilon='256') AND dataset='fb'"
    " GROUP BY dataset, threads, ratio, algo"
    " ORDER BY ratio, threads"
).df()
display(rows.pivot(index='ratio', values='v', columns='algo'))

rows = duckdb.sql(
    " SELECT ratio, algo, MEDIAN(duration_sec) as v FROM df"
    f" WHERE threads=1 AND (algo='hash_join' OR algo='sort_join' or epsilon='256') AND dataset='fb'"
    " AND (algo='lsj_pgm256' OR algo='lsj_flatpgm256' OR algo='lsj_sampledpgm256' OR algo='lsj_sampledflatpgm256')"
    " GROUP BY dataset, threads, ratio, algo"
    " ORDER BY ratio, threads"
).df()
display(rows.pivot(index='ratio', values='v', columns='algo'))

rows = duckdb.sql(
    " SELECT ratio, algo, MEDIAN(duration_sec) as v FROM df"
    f" WHERE threads=1 AND (algo='hash_join' OR algo='sort_join' or epsilon='1024') AND dataset='wiki'"
    " GROUP BY dataset, threads, ratio, algo"
    " ORDER BY ratio, threads"
).df()
display(rows.pivot(index='ratio', values='v', columns='algo'))

rows = duckdb.sql(
    " SELECT ratio, algo, MEDIAN(duration_sec) as v FROM df"
    f" WHERE threads=1 AND (algo='hash_join' OR algo='sort_join' or epsilon='256') AND dataset='wiki'"
    " AND (algo='lsj_pgm256' OR algo='lsj_flatpgm256' OR algo='lsj_sampledpgm256' OR algo='lsj_sampledflatpgm256')"
    " GROUP BY dataset, threads, ratio, algo"
    " ORDER BY ratio, threads"
).df()
display(rows.pivot(index='ratio', values='v', columns='algo'))

rows = duckdb.sql(
    " SELECT ratio, algo, MEDIAN(duration_sec) as v FROM df"
    f" WHERE threads=1 AND (algo='hash_join' OR algo='sort_join' or epsilon='4096') AND dataset='books'"
    " GROUP BY dataset, threads, ratio, algo"
    " ORDER BY ratio, threads"
).df()
display(rows.pivot(index='ratio', values='v', columns='algo'))

rows = duckdb.sql(
    " SELECT ratio, algo, MEDIAN(duration_sec) as v FROM df"
    f" WHERE threads=1 AND (algo='hash_join' OR algo='sort_join' or epsilon='256') AND dataset='osm'"
    " AND (algo='lsj_pgm256' OR algo='lsj_flatpgm256' OR algo='lsj_sampledpgm256' OR algo='lsj_sampledflatpgm256')"
    " GROUP BY dataset, threads, ratio, algo"
    " ORDER BY ratio, threads"
).df()
display(rows.pivot(index='ratio', values='v', columns='algo'))

algo,lsj_btree256,lsj_flatpgm256,lsj_pgm256,lsj_radixspline256,lsj_sampledflatpgm256,sort_join
ratio,,,,,,
1,42.300910,22.431856,27.055335,25.670175,23.229437,11.704229
10,5.834207,3.450734,4.009025,4.307376,3.152880,3.904735
100,1.571960,0.940489,1.313947,1.462793,0.983620,2.998804
1000,0.319080,0.243864,0.343778,0.374326,0.385151,2.560174

algo   lsj_flatpgm256  lsj_pgm256  lsj_sampledflatpgm256
ratio
1           22.431856   27.055335              23.229437
10           3.450734    4.009025               3.152880
100          0.940489    1.313947               0.983620
1000         0.243864    0.343778               0.385151

algo   lsj_radixspline1024  sort_join
ratio
1                10.778464   5.129859
10                3.267205   2.262956
100               0.926267   1.313295
1000              0.414278   1.190710

algo   lsj_flatpgm256  lsj_pgm256  lsj_sampledflatpgm256
ratio
1            9.457123   11.353547              10.117874
10           2.501715    3.032850               3.073691
100          0.561450    0.750796               0.698167
1000         0.208535    0.317465               0.213931

algo   lsj_radixspline4096  sort_join
ratio
1               103.147400  47.431663
10               15.031332  15.704701
100               3.462918  11.254792
1000              2.263213  11.304608

algo   lsj_flatpgm256  lsj_pgm256  lsj_sampledflatpgm256
ratio
1           82.983117  117.044278              88.978646
10          12.694236   16.350766              13.171777
100          3.748309    3.820507               3.968178
1000         1.110650    1.380077               1.210211

In [13]:
rows = duckdb.sql(
    " SELECT ratio, algo, MEDIAN(inner_disk_fetch) as v FROM df"
    f" WHERE threads=1 AND (algo='hash_join' OR algo='sort_join' or epsilon='256') AND dataset='wiki'"
    " GROUP BY dataset, threads, ratio, algo"
    " ORDER BY ratio, threads"
).df()
display(rows.pivot(index='ratio', values='v', columns='algo'))

rows = duckdb.sql(
    " SELECT ratio, algo, MEDIAN(inner_disk_fetch) as v FROM df"
    f" WHERE threads=1 AND (algo='hash_join' OR algo='sort_join' or epsilon='1024') AND dataset='wiki'"
    " GROUP BY dataset, threads, ratio, algo"
    " ORDER BY ratio, threads"
).df()
display(rows.pivot(index='ratio', values='v', columns='algo'))

rows = duckdb.sql(
    " SELECT ratio, algo, MEDIAN(inner_disk_fetch) as v FROM df"
    f" WHERE threads=1 AND (algo='hash_join' OR algo='sort_join' or epsilon='4096') AND dataset='wiki'"
    " GROUP BY dataset, threads, ratio, algo"
    " ORDER BY ratio, threads"
).df()
display(rows.pivot(index='ratio', values='v', columns='algo'))

algo,lsj_btree256,lsj_flatpgm256,lsj_pgm256,lsj_radixspline256,lsj_sampledflatpgm256,sort_join
ratio,,,,,,
1,353270.0,176635.0,176635.0,353270.0,176635.0,353270.0
10,353270.0,176611.0,176610.0,353209.0,176635.0,353270.0
100,348811.0,172933.0,172958.0,345715.0,176405.0,353270.0
1000,149418.0,102884.0,102878.0,194161.0,118522.0,353270.0

algo   lsj_radixspline1024  sort_join
ratio
1                  88318.0   353270.0
10                 88316.0   353270.0
100                88099.0   353270.0
1000               79616.0   353270.0

algo   lsj_radixspline4096  sort_join
ratio
1                  22080.0   353270.0
10                 22080.0   353270.0
100                22079.0   353270.0
1000               21960.0   353270.0

In [14]:
def print_for_dataset(dataset, algos):
    print("## " + dataset)
    algo_filter = ''
    for algo in algos:
        algo_filter = algo_filter + f" OR algo='{algo}'"
    algo_filter = algo_filter[3:]
    rows = duckdb.sql(
        " SELECT ratio, algo, MEDIAN(duration_sec) as v FROM df"
        f" WHERE threads=1  AND dataset='{dataset}'"
        f" AND ({algo_filter})"
        " GROUP BY dataset, threads, ratio, algo"
        " ORDER BY ratio, threads"
    ).df()
    rows = rows.pivot(index='ratio', values='v', columns='algo')
    print(rows[algos].to_markdown())
    rows[algos].to_csv('all_indexes/'+dataset+'.csv')



algos = ['lsj_sampledflatpgm256', 'lsj_btree256',  'sort_join']
#print_for_dataset("fb", algos)
#print_for_dataset("wiki", algos)
print_for_dataset("osm", algos)
print_for_dataset("books", algos)

## osm
|   ratio |   lsj_sampledflatpgm256 |   lsj_btree256 |   sort_join |
|--------:|------------------------:|---------------:|------------:|
|       1 |                88.9786  |      175.609   |     47.7724 |
|      10 |                13.1718  |       22.2175  |     15.3804 |
|     100 |                 3.96818 |        4.68381 |     11.4066 |
|    1000 |                 1.21021 |        1.11332 |     10.7698 |
## books
|   ratio |   lsj_sampledflatpgm256 |   lsj_btree256 |   sort_join |
|--------:|------------------------:|---------------:|------------:|
|       1 |                87.8691  |      174.423   |     47.4317 |
|      10 |                13.3788  |       22.2364  |     15.7047 |
|     100 |                 3.54946 |        4.84053 |     11.2548 |
|    1000 |                 1.20184 |        1.27291 |     11.3046 |

In [34]:
algos = ['lsj_sampledflatpgm256', 'lsj_flatpgm256', 'lsj_radixspline256', 'lsj_rmi' , 'lsj_btree256', 'sort_join']
print_for_dataset("fb", algos)
print_for_dataset("wiki", algos)
print_for_dataset("osm", algos)
print_for_dataset("books", algos)

## fb
|   ratio |   lsj_sampledflatpgm256 |   lsj_flatpgm256 |   lsj_radixspline256 |   lsj_rmi |   lsj_btree256 |   sort_join |
|--------:|------------------------:|-----------------:|---------------------:|----------:|---------------:|------------:|
|       1 |               23.2294   |        22.4319   |            25.6702   | 20.3287   |       42.3009  |    11.7042  |
|      10 |                3.68178  |         3.45073  |             4.30738  |  3.76312  |        5.83421 |     4.45029 |
|     100 |                0.98362  |         1.01192  |             1.46279  |  1.25237  |        1.57196 |     3.12833 |
|    1000 |                0.385151 |         0.353513 |             0.374326 |  0.275802 |        0.31908 |     2.86744 |
## wiki
|   ratio |   lsj_sampledflatpgm256 |   lsj_flatpgm256 |   lsj_radixspline256 |   lsj_btree256 |   sort_join |
|--------:|------------------------:|-----------------:|---------------------:|---------------:|------------:|
|       1 |               10.1179   |         9.45712  |             9.97239  |      19.3136   |     5.38747 |
|      10 |                3.07369  |         2.50171  |             3.14674  |       4.90736  |     2.74042 |
|     100 |                0.698167 |         0.56145  |             0.854485 |       0.8996   |     1.33415 |
|    1000 |                0.213931 |         0.208535 |             0.377251 |       0.322383 |     1.68557 |
## osm
|   ratio |   lsj_sampledflatpgm256 |   lsj_flatpgm256 |   lsj_radixspline256 |   lsj_rmi |   lsj_btree256 |   sort_join |
|--------:|------------------------:|-----------------:|---------------------:|----------:|---------------:|------------:|
|       1 |               72.8033   |        73.47     |             83.6905  |  85.1446  |      175.609   |     45.4784 |
|      10 |                7.99908  |         7.29272  |             13.9856  |  12.8359  |       22.2175  |     15.2134 |
|     100 |                0.840453 |         1.265    |              4.30599 |   4.21186 |        4.68381 |     11.2403 |
|    1000 |                0.146099 |         0.140748 |              1.23905 |   1.68892 |        1.11332 |     10.7955 |
## books
|   ratio |   lsj_sampledflatpgm256 |   lsj_flatpgm256 |   lsj_radixspline256 |   lsj_rmi |   lsj_btree256 |   sort_join |
|--------:|------------------------:|-----------------:|---------------------:|----------:|---------------:|------------:|
|       1 |               72.8343   |        73.6028   |             83.7642  | 78.908    |      174.423   |     45.1136 |
|      10 |                7.2696   |         6.94197  |             13.8679  | 12.7151   |       22.2364  |     15.456  |
|     100 |                0.914571 |         1.16784  |              4.35452 |  3.6482   |        4.84053 |     11.1811 |
|    1000 |                0.128371 |         0.131493 |              1.44302 |  0.936506 |        1.27291 |     10.9385 |

In [29]:
algos = ['lsj_radixspline256', 'lsj_radixspline1024', 'lsj_radixspline4096']
print_for_dataset("fb", algos)
print_for_dataset("wiki", algos)
print_for_dataset("osm", algos)
print_for_dataset("books", algos)

## fb

BinderException: Binder Error: Referenced column "threads" not found in FROM clause!
Candidate bindings: "df.dataset"