In [3]:
import os;
import json;
import builtins
import duckdb
import pandas as pd;
import matplotlib.pyplot as plt


def get_dataset_from_testcase(run):
    return run[0:-2]

def get_dataset_size(dataset):
    if dataset == "osm" or dataset == "books":
        return 800_000_000
    else:
        return 200_000_000

runs = []
dir = '/home/chesetti/Repos/learned_merge_cleanup/sponge/join_all'
for test_case in os.listdir(dir):
    if test_case == 'build':
        continue
    for run_name in os.listdir(os.path.join(dir, test_case, 'outputs', 'results', 'run')):
        json_file = builtins.open(os.path.join(dir, test_case, 'outputs', 'results', 'run', run_name))
        run = (json.load(json_file))
        run['dataset'] = get_dataset_from_testcase(test_case)
        run['dataset_size'] = get_dataset_size(run['dataset'])
        runs.append(run)

dir = '/home/chesetti/Repos/learned_merge_cleanup/sponge/string_keys'
for test_case in os.listdir(dir):
    if test_case == 'build':
        continue
    for run_name in os.listdir(os.path.join(dir, test_case, 'outputs', 'results', 'run')):
        json_file = builtins.open(os.path.join(dir, test_case, 'outputs', 'results', 'run', run_name))
        run = (json.load(json_file))
        run['dataset'] = get_dataset_from_testcase(test_case)
        run['dataset_size'] = get_dataset_size(run['dataset'])
        runs.append(run)
df = pd.json_normalize(runs)
print(df.columns)

Index(['command', 'dataset', 'dataset_size', 'result.checksum',
       'result.duration_ns', 'result.duration_sec', 'result.inner_disk_fetch',
       'result.inner_disk_fetch_size', 'result.inner_total_bytes_fetched',
       'result.num_output_keys', 'result.outer_disk_fetch',
       'result.outer_disk_fetch_size', 'result.outer_total_bytes_fetched',
       'spec.algo', 'spec.algo_name', 'spec.check_checksum', 'spec.common_key',
       'spec.index.epsilon', 'spec.index.search', 'spec.index.type',
       'spec.inner_table', 'spec.key_size', 'spec.key_type',
       'spec.load_sstable_in_mem', 'spec.name', 'spec.num_threads',
       'spec.outer_table', 'spec.result_path', 'spec.value_size',
       'spec.write_result_to_disk', 'spec.index.leaf_size_in_pages'],
      dtype='object')

In [4]:
def get_index_type(index):
    if "btree" in index:
        return "BTREE"
    if "pgm" in index:
        return "PGM"
    return "NA"

def get_index_variant(index):
    if index == "sort_join" or index == "hash_join":
        return "NA"
    pos = index.find("_")
    return index[pos+1:-1]

df["threads"] = df["spec.num_threads"]
df["epsilon"] = df["spec.index.epsilon"]
df["duration_sec"] = df["result.duration_ns"] / (1000000000)
df["ratio"] = df["spec.common_key"]
df["thput"] = (df["result.num_output_keys"] / df["ratio"]) / (df["result.duration_ns"] / (1000000000))
df["algo"] = df["spec.algo_name"]
df["join_algo"] = df["spec.algo"]
df["index_type"] = df["spec.algo_name"].map(lambda x: get_index_type(x))
df["index_variant"] = df["spec.algo_name"].map(lambda x: get_index_variant(x))
df["inner_bytes_fetched"] = df["result.inner_total_bytes_fetched"]
display(df["algo"].unique())
display(df["dataset"].unique())
display(df["index_type"].unique())

array(['lsj_sampledflatpgm256', 'inlj_flatpgm4096', 'lsj_btree4096',
       'inlj_sampledflatpgm4096', 'inlj_flatpgm1024', 'hash_join',
       'inlj_pgm4096', 'sort_join', 'inlj_pgm1024', 'inlj_btree1024',
       'lsj_sampledflatpgm1024', 'inlj_btree256',
       'inlj_sampledflatpgm1024', 'lsj_pgm256', 'lsj_btree1024',
       'lsj_btree256', 'inlj_flatpgm256', 'lsj_flatpgm1024',
       'inlj_sampledflatpgm256', 'lsj_sampledflatpgm4096', 'inlj_pgm256',
       'lsj_pgm4096', 'lsj_pgm1024', 'lsj_flatpgm4096', 'lsj_flatpgm256',
       'inlj_btree4096'], dtype=object)

array(['fb', 'books', 'osm', 'uniform_dense', 'lognormal',
       'uniform_sparse', 'normal', 'wiki', 'string_keys', 'string_keys_'],
      dtype=object)

array(['PGM', 'BTREE', 'NA'], dtype=object)

In [5]:
# SingleThread, HJ vs SJ vs INLJ(BTree256) vs INLJ(PGM256) vs LS(BTree256) vs LS(PGM256)
def plot_dataset_join_duration(dataset):
    rows = duckdb.sql(
        "SELECT ratio, threads, algo, MEDIAN(duration_sec) as d, MEDIAN(thput) as t FROM df " 
        "WHERE" 
        "   (algo='hash_join' OR algo='sort_join' OR algo='inlj_btree256' OR algo='inlj_pgm256' OR "
        "   algo='lsj_btree256' OR algo='lsj_flatpgm256')" 
        "   AND threads=1"
        f"   AND dataset='{dataset}'"
        "GROUP BY dataset, ratio, threads, algo"
    ).df()
    result = (rows.pivot(index='ratio', values='d', columns=['algo']))
    ## Save to CSV
    os.makedirs('single_thread_csv_ssd_latency/', exist_ok=True)
    result.to_csv(f'single_thread_csv_ssd_latency/{dataset}.csv')
    return result

real_datasets = ['fb', 'wiki', 'osm', 'books']
synth_datasets = ['uniform_dense', 'uniform_sparse', 'normal', 'lognormal', 'string_keys']

for dataset in real_datasets:
    display(dataset)
    display(plot_dataset_join_duration(dataset))

for dataset in synth_datasets:
    display(dataset)
    display(plot_dataset_join_duration(dataset))

print ('DATA BYTES')


# SingleThread, HJ vs SJ vs INLJ(BTree256) vs INLJ(PGM256) vs LS(BTree256) vs LS(PGM256)
def plot_dataset_bytes_fetched(dataset):
    rows = duckdb.sql(
        "SELECT ratio, threads, algo, MEDIAN(inner_bytes_fetched) as d, MEDIAN(thput) as t FROM df " 
        "WHERE" 
        "   (algo='hash_join' OR algo='sort_join' OR algo='inlj_btree256' OR algo='inlj_pgm256' OR "
        "   algo='lsj_btree256' OR algo='lsj_flatpgm256')" 
        "   AND threads=1"
        f"   AND dataset='{dataset}'"
        "GROUP BY dataset, ratio, threads, algo"
    ).df()
    result = (rows.pivot(index='ratio', values='d', columns=['algo']))
    ## Save to CSV
    os.makedirs('single_thread_csv_bytes/', exist_ok=True)
    result.to_csv(f'single_thread_csv_bytes/{dataset}.csv')
    return result

real_datasets = ['fb', 'wiki', 'osm', 'books']
synth_datasets = ['uniform_dense', 'uniform_sparse', 'normal', 'lognormal', 'string_keys']

for dataset in real_datasets:
    display(dataset)
    display(plot_dataset_bytes_fetched(dataset))

for dataset in synth_datasets:
    display(dataset)
    display(plot_dataset_bytes_fetched(dataset))

'fb'

algo,hash_join,inlj_btree256,inlj_pgm256,lsj_btree256,lsj_flatpgm256,sort_join
ratio,,,,,,
1,92.803386,53.067202,39.427941,47.774045,25.976550,15.907270
10,49.446850,6.178218,4.912952,6.495105,4.075511,4.825520
100,37.227181,1.664028,1.084884,1.634213,1.199437,3.364797
1000,14.757411,0.259721,0.352090,0.315716,0.285341,3.176952

'wiki'

algo,hash_join,inlj_btree256,inlj_pgm256,lsj_btree256,lsj_flatpgm256,sort_join
ratio,,,,,,
1,37.334655,23.540610,15.039791,20.846256,11.690900,6.969193
10,22.695847,5.059676,3.505500,4.941911,3.507018,2.795611
100,16.403791,0.875864,1.013105,0.882262,0.615757,1.422261
1000,6.730158,0.222480,0.223985,0.222210,0.216568,1.245280

'osm'

algo,hash_join,inlj_btree256,inlj_pgm256,lsj_btree256,lsj_flatpgm256,sort_join
ratio,,,,,,
1,394.417244,220.285748,166.162271,200.463251,103.676759,65.136807
10,212.340018,25.399285,21.143848,24.945802,14.577316,16.733143
100,171.108191,5.232424,4.587406,5.169243,3.353662,11.268316
1000,116.305041,1.203590,1.057887,0.917966,0.987858,10.997142

'books'

algo,hash_join,inlj_btree256,inlj_pgm256,lsj_btree256,lsj_flatpgm256,sort_join
ratio,,,,,,
1,398.251161,220.221972,155.472267,196.788203,104.705014,65.104509
10,208.087068,24.477425,19.432855,24.280784,15.159822,17.822567
100,165.030208,4.772314,4.422834,5.067250,3.714432,11.729989
1000,105.147476,1.214799,1.274829,1.064794,1.214564,11.361769

'uniform_dense'

algo,hash_join,inlj_btree256,inlj_pgm256,lsj_btree256,lsj_flatpgm256,sort_join
ratio,,,,,,
1,91.995295,52.255048,25.001485,47.124268,26.093486,16.466502
10,50.385091,6.466812,3.425246,6.497088,3.862628,4.696147
100,37.449092,1.223725,1.029831,1.187741,0.799342,2.935965
1000,14.513171,0.258679,0.294243,0.247661,0.259095,2.729532

'uniform_sparse'

algo,hash_join,inlj_btree256,inlj_pgm256,lsj_btree256,lsj_flatpgm256,sort_join
ratio,,,,,,
1,91.047514,52.301702,36.662256,48.577115,26.616213,17.222768
10,49.506231,5.985692,4.701640,6.052254,3.820223,4.800495
100,38.401967,1.207014,1.012684,1.198434,1.123010,3.490063
1000,14.258768,0.252391,0.272613,0.254787,0.322005,2.731898

'normal'

algo,hash_join,inlj_btree256,inlj_pgm256,lsj_btree256,lsj_flatpgm256,sort_join
ratio,,,,,,
1,94.056723,54.062095,29.698941,47.962588,26.738348,16.558630
10,47.265245,6.727578,3.945524,5.999719,3.541300,5.026393
100,37.498558,1.192461,0.938083,1.193659,1.072242,2.894747
1000,14.713410,0.243950,0.312992,0.305125,0.305724,2.695198

'lognormal'

algo,hash_join,inlj_btree256,inlj_pgm256,lsj_btree256,lsj_flatpgm256,sort_join
ratio,,,,,,
1,91.594071,54.251634,33.305641,48.218088,24.873390,17.354602
10,50.659646,6.138937,4.297023,6.553460,4.182600,4.595661
100,39.186771,1.189923,1.006116,1.191112,1.075444,2.879593
1000,15.736142,0.239541,0.258540,0.303619,0.306435,2.703660

'string_keys'

algo   hash_join  inlj_btree256  lsj_btree256  lsj_flatpgm256  sort_join
ratio
1      36.379383      52.539736     52.595917       11.851185   6.903735
10     35.512152       9.847776      9.951254        2.415511   2.184780
100    21.267183       1.311293      1.317681        0.519717   1.134266
1000   10.063567       0.236521      0.234677        0.169846   1.003297

DATA BYTES

'fb'

algo,hash_join,inlj_btree256,inlj_pgm256,lsj_btree256,lsj_flatpgm256,sort_join
ratio,,,,,,
1,3.200000e+09,3.200000e+09,8.586481e+09,3.200000e+09,3.200000e+09,3.200000e+09
10,3.200000e+09,3.200000e+09,7.968676e+09,3.200000e+09,3.198576e+09,3.200000e+09
100,3.200000e+09,2.952733e+09,4.386897e+09,2.952733e+09,3.009724e+09,3.200000e+09
1000,3.200000e+09,7.223910e+08,1.195606e+09,7.223910e+08,1.182605e+09,3.199934e+09

'wiki'

algo,hash_join,inlj_btree256,inlj_pgm256,lsj_btree256,lsj_flatpgm256,sort_join
ratio,,,,,,
1,1.446992e+09,1.446992e+09,4.016357e+09,1.446992e+09,1.446992e+09,1.446992e+09
10,1.446992e+09,1.446992e+09,3.860335e+09,1.446992e+09,1.446796e+09,1.446992e+09
100,1.446992e+09,1.429408e+09,2.702582e+09,1.429408e+09,1.417191e+09,1.446992e+09
1000,1.446992e+09,6.124012e+08,8.919476e+08,6.124012e+08,8.440736e+08,1.446990e+09

'osm'

algo,hash_join,inlj_btree256,inlj_pgm256,lsj_btree256,lsj_flatpgm256,sort_join
ratio,,,,,,
1,1.280000e+10,1.280000e+10,3.488052e+10,1.280000e+10,1.280000e+10,1.280000e+10
10,1.280000e+10,1.280000e+10,3.243318e+10,1.280000e+10,1.279521e+10,1.280000e+10
100,1.280000e+10,1.181016e+10,1.760682e+10,1.181016e+10,1.204098e+10,1.280000e+10
1000,1.280000e+10,2.891776e+09,4.775428e+09,2.891776e+09,4.724015e+09,1.279998e+10

'books'

algo,hash_join,inlj_btree256,inlj_pgm256,lsj_btree256,lsj_flatpgm256,sort_join
ratio,,,,,,
1,1.280000e+10,1.280000e+10,3.455293e+10,1.280000e+10,1.280000e+10,1.280000e+10
10,1.280000e+10,1.280000e+10,3.243208e+10,1.280000e+10,1.279730e+10,1.280000e+10
100,1.280000e+10,1.181062e+10,1.732643e+10,1.181062e+10,1.205007e+10,1.280000e+10
1000,1.280000e+10,2.891284e+09,4.756969e+09,2.891284e+09,4.711364e+09,1.280000e+10

'uniform_dense'

algo,hash_join,inlj_btree256,inlj_pgm256,lsj_btree256,lsj_flatpgm256,sort_join
ratio,,,,,,
1,3.200000e+09,3.200000e+09,7.423205e+09,3.200000e+09,3.200000e+09,3.200000e+09
10,3.200000e+09,3.200000e+09,6.802921e+09,3.200000e+09,3.198022e+09,3.200000e+09
100,3.200000e+09,2.953056e+09,3.420777e+09,2.953056e+09,2.902650e+09,3.200000e+09
1000,3.200000e+09,7.231816e+08,1.136624e+09,7.231816e+08,1.133478e+09,3.199963e+09

'uniform_sparse'

algo,hash_join,inlj_btree256,inlj_pgm256,lsj_btree256,lsj_flatpgm256,sort_join
ratio,,,,,,
1,3.200000e+09,3.200000e+09,8.725606e+09,3.200000e+09,3.200000e+09,3.200000e+09
10,3.200000e+09,3.200000e+09,8.221691e+09,3.200000e+09,3.199547e+09,3.200000e+09
100,3.200000e+09,2.953175e+09,4.358390e+09,2.953175e+09,3.014459e+09,3.200000e+09
1000,3.200000e+09,7.227965e+08,1.189208e+09,7.227965e+08,1.177657e+09,3.199988e+09

'normal'

algo,hash_join,inlj_btree256,inlj_pgm256,lsj_btree256,lsj_flatpgm256,sort_join
ratio,,,,,,
1,3.200000e+09,3.200000e+09,8.902339e+09,3.200000e+09,3.200000e+09,3.200000e+09
10,3.200000e+09,3.200000e+09,8.070170e+09,3.200000e+09,3.194599e+09,3.200000e+09
100,3.200000e+09,2.953781e+09,4.437716e+09,2.953781e+09,2.982029e+09,3.200000e+09
1000,3.200000e+09,7.225999e+08,1.191346e+09,7.225999e+08,1.177739e+09,3.199992e+09

'lognormal'

algo,hash_join,inlj_btree256,inlj_pgm256,lsj_btree256,lsj_flatpgm256,sort_join
ratio,,,,,,
1,3.200000e+09,3.200000e+09,9.978460e+09,3.200000e+09,3.200000e+09,3.200000e+09
10,3.200000e+09,3.200000e+09,9.279498e+09,3.200000e+09,3.198694e+09,3.200000e+09
100,3.200000e+09,2.951574e+09,5.075681e+09,2.951574e+09,3.053799e+09,3.200000e+09
1000,3.200000e+09,7.230669e+08,1.230225e+09,7.230669e+08,1.210745e+09,3.199992e+09

'string_keys'

algo      hash_join  inlj_btree256  lsj_btree256  lsj_flatpgm256     sort_join
ratio
1      3.200000e+09   1.600004e+09  1.600004e+09    1.600008e+09  1.600000e+09
10     3.200000e+09   1.600004e+09  1.600004e+09    1.599971e+09  1.600000e+09
100    3.200000e+09   1.590239e+09  1.590239e+09    1.573405e+09  1.599996e+09
1000   3.200000e+09   6.414991e+08  6.414991e+08    7.982531e+08  1.600000e+09

In [6]:
# Effect of Epsilon on INLJ (BTree and PGM)
def plot_epsilon_inlj(dataset):
    rows = duckdb.sql(
        "SELECT ratio, algo, join_algo, epsilon, MEDIAN(duration_sec) as d, MEDIAN(thput) as t FROM df " 
        "WHERE" 
        "   join_algo = 'inlj'"
        "   AND threads=1"
        f"   AND dataset='{dataset}'"
        "GROUP BY dataset, ratio, algo, join_algo, epsilon"
    ).df()
    return rows.pivot(index='ratio', values='d', columns=['algo', 'epsilon'])

for dataset in real_datasets:
    display(dataset)
    display(plot_epsilon_inlj(dataset))

for dataset in synth_datasets:
    display(dataset)
    display(plot_epsilon_inlj(dataset))

'fb'

algo,inlj_flatpgm4096,inlj_sampledflatpgm4096,inlj_btree1024,inlj_btree4096,inlj_btree256,inlj_pgm256,inlj_flatpgm1024,inlj_flatpgm256,inlj_pgm1024,inlj_sampledflatpgm256,inlj_sampledflatpgm1024,inlj_pgm4096
epsilon,4096.0,4096.0,1024.0,4096.0,256.0,256.0,1024.0,256.0,1024.0,256.0,1024.0,4096.0
ratio,,,,,,,,,,,,
1,36.860210,37.738168,54.454780,53.186117,53.067202,39.427941,36.694180,35.735968,38.800283,39.077775,39.386363,42.717257
10,5.570609,5.405943,6.049074,5.819146,6.178218,4.912952,5.253616,4.782187,5.297466,5.984620,5.623032,5.850861
100,1.833962,1.536952,1.130245,1.093045,1.664028,1.084884,1.593616,1.418238,1.199611,1.619190,1.396686,1.413768
1000,0.775226,0.645554,0.398953,0.510789,0.259721,0.352090,0.485742,0.346613,0.491207,0.377439,0.427322,0.787943

'wiki'

algo,inlj_sampledflatpgm4096,inlj_btree1024,inlj_sampledflatpgm1024,inlj_btree4096,inlj_flatpgm4096,inlj_pgm256,inlj_btree256,inlj_sampledflatpgm256,inlj_pgm1024,inlj_pgm4096,inlj_flatpgm256,inlj_flatpgm1024
epsilon,4096.0,1024.0,1024.0,4096.0,4096.0,256.0,256.0,256.0,1024.0,4096.0,256.0,1024.0
ratio,,,,,,,,,,,,
1,17.307899,22.996426,16.447396,21.834449,15.443946,15.039791,23.540610,15.234307,15.998415,16.979243,13.750013,14.622424
10,4.318298,5.454602,4.215259,4.802448,3.783417,3.505500,5.059676,4.056870,3.834758,4.059837,3.788520,3.527932
100,1.062199,0.822400,1.003368,0.808017,0.932598,1.013105,0.875864,0.931938,0.840494,0.964979,0.718000,0.812739
1000,0.424065,0.276095,0.316107,0.292301,0.400498,0.223985,0.222480,0.306665,0.293112,0.404468,0.222146,0.288934

'osm'

algo,inlj_flatpgm1024,inlj_btree1024,inlj_sampledflatpgm1024,inlj_sampledflatpgm256,inlj_btree4096,inlj_flatpgm4096,inlj_sampledflatpgm4096,inlj_btree256,inlj_pgm256,inlj_flatpgm256,inlj_pgm4096,inlj_pgm1024
epsilon,1024.0,1024.0,1024.0,256.0,4096.0,4096.0,4096.0,256.0,256.0,256.0,4096.0,1024.0
ratio,,,,,,,,,,,,
1,144.453673,220.839598,155.611260,154.527524,224.079986,149.348301,158.512082,220.285748,166.162271,138.056128,175.335050,170.355877
10,18.774109,24.480700,21.997978,21.707538,25.333986,20.438603,22.462241,25.399285,21.143848,18.095678,23.144047,22.145996
100,4.711144,4.603469,5.864190,5.397311,4.304702,5.432549,6.752207,5.232424,4.587406,3.990672,5.817004,5.385337
1000,1.476010,1.696912,1.547528,1.140860,1.832916,2.609155,2.383607,1.203590,1.057887,1.027413,2.322557,1.502020

'books'

algo,inlj_btree256,inlj_pgm256,inlj_pgm4096,inlj_flatpgm4096,inlj_sampledflatpgm4096,inlj_pgm1024,inlj_flatpgm256,inlj_btree1024,inlj_sampledflatpgm1024,inlj_btree4096,inlj_flatpgm1024,inlj_sampledflatpgm256
epsilon,256.0,256.0,4096.0,4096.0,4096.0,1024.0,256.0,1024.0,1024.0,4096.0,1024.0,256.0
ratio,,,,,,,,,,,,
1,220.221972,155.472267,156.799033,141.357813,141.953985,160.410121,135.357829,220.607991,142.122431,222.726587,138.770514,141.599183
10,24.477425,19.432855,20.635646,19.471097,20.252489,20.416732,17.705866,24.648594,20.311096,25.605078,18.547788,21.059566
100,4.772314,4.422834,5.764166,5.455009,5.925539,5.024035,3.843942,4.207409,5.130841,4.202466,4.375195,5.231396
1000,1.214799,1.274829,2.603389,2.206440,2.221548,1.429928,1.270190,1.680532,1.542952,2.084253,1.414111,1.077513

'uniform_dense'

algo,inlj_btree1024,inlj_pgm1024,inlj_sampledflatpgm1024,inlj_btree4096,inlj_flatpgm256,inlj_sampledflatpgm4096,inlj_flatpgm1024,inlj_flatpgm4096,inlj_pgm4096,inlj_btree256,inlj_sampledflatpgm256,inlj_pgm256
epsilon,1024.0,1024.0,1024.0,4096.0,256.0,4096.0,1024.0,4096.0,4096.0,256.0,256.0,256.0
ratio,,,,,,,,,,,,
1,54.116375,27.148338,32.456350,52.614582,25.117645,32.89104,25.809003,27.749484,28.410640,52.255048,26.240620,25.001485
10,6.134359,3.864290,4.916618,5.980902,3.143861,4.42535,3.342284,3.853741,3.514409,6.466812,4.481353,3.425246
100,1.477691,1.129804,1.416474,1.464370,1.032683,1.07432,0.879405,0.956024,0.961834,1.223725,1.063534,1.029831
1000,0.465102,0.401361,0.381778,0.462840,0.303042,0.48453,0.396898,0.464267,0.566964,0.258679,0.340730,0.294243

'uniform_sparse'

algo,inlj_sampledflatpgm1024,inlj_pgm4096,inlj_pgm256,inlj_flatpgm4096,inlj_flatpgm256,inlj_flatpgm1024,inlj_btree1024,inlj_sampledflatpgm256,inlj_pgm1024,inlj_btree4096,inlj_sampledflatpgm4096,inlj_btree256
epsilon,1024.0,4096.0,256.0,4096.0,256.0,1024.0,1024.0,256.0,1024.0,4096.0,4096.0,256.0
ratio,,,,,,,,,,,,
1,35.154202,37.755019,36.662256,35.219507,32.802448,34.293825,55.245917,32.721013,36.347464,53.443362,36.074363,52.301702
10,4.952161,5.537722,4.701640,4.766491,4.369059,4.565168,6.570872,5.214795,5.260598,6.335806,5.277087,5.985692
100,1.256754,1.740371,1.012684,1.264624,0.969279,1.108373,1.071655,1.236354,1.513845,1.442828,1.731077,1.207014
1000,0.395775,0.547029,0.272613,0.549831,0.322530,0.372511,0.376210,0.359669,0.372605,0.488717,0.564094,0.252391

'normal'

algo,inlj_flatpgm1024,inlj_btree1024,inlj_btree256,inlj_flatpgm256,inlj_btree4096,inlj_pgm4096,inlj_flatpgm4096,inlj_sampledflatpgm1024,inlj_sampledflatpgm256,inlj_sampledflatpgm4096,inlj_pgm1024,inlj_pgm256
epsilon,1024.0,1024.0,256.0,256.0,4096.0,4096.0,4096.0,1024.0,256.0,4096.0,1024.0,256.0
ratio,,,,,,,,,,,,
1,29.423931,56.033252,54.062095,27.696246,53.901132,35.679257,31.833445,34.092265,30.905788,35.685901,32.682569,29.698941
10,4.082723,6.414867,6.727578,3.720996,6.607661,5.019567,5.038547,5.635330,5.585452,6.696616,4.791668,3.945524
100,1.510040,1.462578,1.192461,0.913872,1.394548,1.924672,1.433930,1.748598,1.640410,2.257273,1.569407,0.938083
1000,0.422447,0.424038,0.243950,0.306580,0.538436,0.732859,0.734382,0.382800,0.278286,0.582767,0.360370,0.312992

'lognormal'

algo,inlj_pgm1024,inlj_btree256,inlj_btree1024,inlj_flatpgm256,inlj_sampledflatpgm256,inlj_pgm4096,inlj_pgm256,inlj_sampledflatpgm4096,inlj_btree4096,inlj_sampledflatpgm1024,inlj_flatpgm4096,inlj_flatpgm1024
epsilon,1024.0,256.0,1024.0,256.0,256.0,4096.0,256.0,4096.0,4096.0,1024.0,4096.0,1024.0
ratio,,,,,,,,,,,,
1,32.894151,54.251634,55.068840,27.484243,31.509494,37.297779,33.305641,36.831732,52.642450,34.070140,32.922510,29.172672
10,4.741701,6.138937,6.585124,3.737744,5.766262,6.134477,4.297023,7.009174,5.840396,6.068160,5.242064,4.229369
100,1.235123,1.189923,1.449490,0.945974,1.258313,2.442943,1.006116,2.254006,1.015438,1.535502,1.744232,1.184007
1000,0.373348,0.239541,0.427705,0.310651,0.339300,0.837495,0.258540,0.843014,0.438325,0.400146,0.622090,0.405674

'string_keys'

algo,inlj_btree1024,inlj_btree4096,inlj_flatpgm4096,inlj_flatpgm1024,inlj_btree256,inlj_flatpgm256
epsilon,1024.0,4096.0,4096.0,1024.0,256.0,256.0
ratio,,,,,,
1,41.593319,38.215661,15.270117,14.372193,52.539736,13.472333
10,7.672317,7.218117,3.125303,3.119002,9.847776,2.888304
100,1.041535,0.973360,0.730559,0.700993,1.311293,0.593516
1000,0.317576,0.289603,0.350456,0.242440,0.236521,0.167406

In [9]:
def plot_dataset_relative():
    rows = duckdb.sql(
        "SELECT ratio, dataset, algo, MEDIAN(duration_sec) as d FROM df " 
        "WHERE" 
        "   (algo='hash_join' OR algo='sort_join' OR algo='inlj_btree256' OR algo='inlj_pgm256' OR "
        "   algo='lsj_btree256' OR algo='lsj_flatpgm256')" 
        "   AND threads=1"
        "GROUP BY dataset, ratio, threads, algo"
    ).df()
    result = rows.pivot()
    return rows
plot_dataset_relative()

     ratio      dataset            algo           d
0        1          osm       hash_join  394.417244
1       10    lognormal       hash_join   50.659646
2      100       normal       hash_join   37.498558
3        1          osm       sort_join   65.136807
4       10    lognormal       sort_join    4.595661
..     ...          ...             ...         ...
207      1  string_keys   inlj_btree256   52.539736
208     10  string_keys   inlj_btree256    9.847776
209   1000         wiki     inlj_pgm256    0.223985
210    100         wiki    lsj_btree256    0.882262
211    100         wiki  lsj_flatpgm256    0.615757

[212 rows x 4 columns]